config/routes.rb
Rails.application.routes.draw do

  get "/static_pages/:page", to: "static_pages#show"
  root "static_pages#show", page: "home"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "signup", to: "users#new"
  post "signup", to: "users#create"
  resources :users, except: [:index, :destroy]

  namespace :admin do
    resources :users, only: [:index, :destroy, :show]
    resources :subjects
    resources :questions
  end
end

app/models/subject.rb
class Subject < ApplicationRecord

  has_many :questions, dependent: :destroy
  has_many :suggest_questions, dependent: :destroy
  has_many :exams, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: {maximum: 25}
  validates :duration, presence: true, numericality: {only_integer: true}
  validates :number_question, presence: true, numericality: {only_integer: true}
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin
  before_action :find_subject, except: [:index, :new, :create]

  def index
    @subjects = Subject.paginate page: params[:page]
  end

  def new
    @subject = Subject.new
  end
  
  def create
    @subject = Subject.new subject_params
    if @subject.save
      flash.now[:success] = t "controllers.admin.subject.success"
      redirect_to admin_subjects_path @subject
    else
      flash.now[:danger] = t "controllers.admin.subject.fail"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @subject.update_attributes subject_params
      flash[:success] = t "controllers.admin.subject.update"
      redirect_to admin_subjects_path
    else
      render :edit
    end
  end

  def destroy
    if @subject.destroy 
      flash[:success] = t "controllers.admin.subject.flash.delete.success"
    else
      flash[:danger] = t "controllers.admin.subject.flash.delete.fail"
    end
    redirect_to admin_subjects_path
  end

  private
  def find_subject
    @subject = Subject.find_by id: params[:id]
    if @subject.nil?
      flash[:danger] = t "controllers.admin.subject.danger"
      redirect_to admin_subjects_path
    end
  end

  def subject_params
    params.require(:subject).permit :name, :duration, :number_question,
      questions_attributes: [:id, :content, :subject_id]
  end
end

app/views/admin/subjects/_subject_form.html.erb
<%= form_for [:admin, @subject] do |f| %>
  <%= render "shared/error_messages", object: @subject %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :duration %>
  <%= f.text_field :duration, class: "form-control" %>

  <%= f.label :number_question %>
  <%= f.text_field :number_question, class: "form-control" %>

  <%= f.submit yield(:button_text) , class: "btn btn-primary" %>
<% end %>

app/views/admin/subjects/edit.html.erb
<% provide :title, t("admin.subject.edit") %>
<% provide :button_text, t("admin.subject.button") %>
<h1><%= t "admin.subject.edit" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "subject_form" %>
  </div>
</div>

app/views/admin/subjects/index.html.erb
<% provide :title, t("admin.subject.title") %>
<h1><%= t "admin.subject.title" %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t "admin.subject.stt" %></th>
      <th><%= t "admin.subject.name" %></th>
      <th><%= t "admin.subject.number" %></th>
      <th><%= t "admin.subject.duration" %></th>
      <th><%= t "admin.subject.action" %></th>
    </tr>
  </thead>
  <tbody>
    <% @subjects.each.with_index 1 do |subject, index| %>
      <tr>
        <td><%= index %></td>
        <td><%= link_to subject.name, [:admin, subject] %></td>
        <td><%= subject.number_question %></td>
        <td><%= subject.duration %></td>
        <td>
          <% unless current_user.current_user? @user %>
            <%= link_to t("admin.subject.delete"), [:admin, subject], method: :delete,
              data: {confirm: t("controllers.admin.subject.delete")} %> | 
            <%= link_to t("admin.subject.edit"),
              edit_admin_subject_path(subject) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t("admin.subject.new"), new_admin_subject_path(@subject) %>

app/views/admin/subjects/new.html.erb
<% provide :title, t("admin.subject.create") %>
<% provide :button_text, t("admin.subject.button2") %>
<h1><%= t "admin.subject.create" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "subject_form" %>
  </div>
</div>