config/routes.rb
Rails.application.routes.draw do

  get "/static_pages/:page", to: "static_pages#show"
  root "static_pages#show", page: "home"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "signup", to: "users#new"
  post "signup", to: "users#create"
  resources :users, except: [:index, :destroy]

  namespace :admin do
    resources :users, only: [:index, :destroy, :show]
    resources :subjects
    resources :questions
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject

  has_many :answers, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :exams, through: :results

  validates :content, presence: true
  accepts_nested_attributes_for :answers, reject_if: :all_blank
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action :logged_in_user, :verify_admin
  before_action :find_question, except: [:index, :new, :create]
  before_action :load_subjects, only: :new

  def index
    @questions = Question.paginate page: params[:page]
  end

  def new
    @subjects = Subject.all
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    if @question.save
      @subject = @question.subject
      flash.now[:success] = t "controllers.admin.question.create"
      redirect_to admin_questions_path @question
    else
      load_subjects
      flash.now[:danger] = t "controllers.admin.question.fail"
      render :new
    end
  end

  def update
    if @question.update_attributes question_params
      flash[:success] = t "controllers.admin.question.success"
      redirect_to admin_questions_path
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      flash[:success] = t "controllers.admin.question.delete"
    else
      flash[:danger] = t "controllers.admin.question.not"
    end
    redirect_to admin_questions_path
  end

  private
  def load_subjects
    @subjects = Subject.all
  end

  def find_question
    @question = Question.find_by id: params[:id]
    if @question.nil?
      flash[:danger] = t "controllers.admin.question.danger"
      redirect_to admin_questions_path
    end
  end
 
  def question_params
    params.require(:question).permit :content, :subject_id,
      answers_attributes: [:id, :content, :is_correct, :question_id, :_destroy]
  end
end

app/views/admin/questions/_answer_fields.html.erb
<div class="form-group choice_question">
  <div class="form-group">
    <%= f.label t("admin.answer.answer") %>
  </div>
  <div class="col-md-12">
    <div class="col-md-8">
      <%= f.text_field :content, label: false, class: "form-control" %>
    </div>
    <div class="col-md-3 space-top-remove">
      <div class="form-group">
        <%= f.check_box :is_correct, class: "answers_checkbox" %>
      </div>
      <div class="form-group">
        <%= f.hidden_field :_destroy %>
      </div>
      <div class="form-group">
        <%= f.label :true %>
      </div>
    </div>
    <div class="col-md-1 space-top-remove">
      <%= link_to_remove_fields t("admin.answer.remove"), f %>
    </div>
  </div>
</div>

app/views/admin/questions/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="modal-header"><h1><%= yield :modal_title %></h1></div>
      <%= form_for [:admin, @subject, @question] do |f| %>
      <div class="modal-body">
        <div class="form_errors">
          <%= render "shared/error_messages", object: @question %>
        </div>
        <div class="form-group">
          <%= f.label :subject_id %>
          <%= f.collection_select :subject, @subjects, :id, :name %>
        </div>
        <div class="form-group">
          <%= f.label :content %>
          <%= f.text_field :content, class: "form-control" %>
        </div>
        <div id ="answers_field">
          <%= f.fields_for :answers do |answer_builder| %>
            <%= render "answer_fields", f: answer_builder %>
          <% end %>
          <div id ="answer_field">
          </div>
          <div class="add_fields">
            <%= link_to_add_fields t("admin.answer.add"), f, :answers %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <span class="pull-right">
          <%= f.submit t("admin.question.create"), class: "btn btn-primary" %>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/questions/edit.html.erb
<% provide :title, t("admin.question.edit") %>
<% provide :button_text, t("admin.question.button") %>
<h1><%= t "admin.question.edit" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @question] do |f| %>
      <%= render "shared/error_messages", object: @question %>
      <div class="for-group">
	    <%= f.label :subject %>
        <%= f.collection_select :subject_id, Subject.all, :id, :name %>
      </div>

      <div class="for-group">
	    <%= f.label :content %>
	    <%= f.text_area :content, rows: 4, class: "form-control" %>
      </div>
	  <%= f.submit t("admin.question.update") , class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/questions/index.html.erb
<% provide :title, t("admin.question.title") %>
<h1><%= t "admin.question.h1" %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t "admin.question.stt" %></th>
      <th><%= t "admin.question.subject_id" %></th>
      <th><%= t "admin.question.content" %></th>
      <th><%= t "admin.question.answer" %></th>
      <th><%= t "admin.question.action" %></th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each.with_index 1 do |question, index| %>
      <tr>
        <td><%= index %></td>
        <td><%= link_to question.subject.name %></td>
        <td><%= question.content %></td>
        <td></td>
      	<td>
      	  <% unless current_user.current_user? @user %>
            <%= link_to t("admin.question.delete"), [:admin, question],
              method: :delete,
              data: {confirm: t("controllers.admin.sure")} %> | 
            <%= link_to t("admin.question.edit"),
              edit_admin_question_path(question) %>
          <% end %>
      	</td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t("admin.question.new"), new_admin_question_path(@question) %>

app/views/admin/questions/new.html.erb
<% provide :title, t("admin.question.new") %>
<% provide :button_text, t("admin.question.button2") %>
<h1><%= t "admin.question.new" %></h1>

<%= render "form" %>

app/views/admin/questions/show.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for [:admin, @question] do |f| %>
      <%= render "shared/error_messages", object: @question %>

      <%= render "question_fields", f: f %>
      <div class="row">
        <div class="col-md-6">
          <%= link_to t("suggest_question.delete"),
            admin_questions_path(@question), method: :delete,
            data: {confirm: t("delete.confirm")}, class: "btn btn-danger" %>
        </div>
        <div class="col-md-6">
          <%= f.submit t("edit.submit"), class: "btn btn-primary",
            id: "question-submit" %>
        </div>
      </div>
    <% end %>
  </div>
</div>