config/routes.rb
Rails.application.routes.draw do

  get "/static_pages/:page", to: "static_pages#show"
  root "static_pages#show", page: "home"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "signup", to: "users#new"
  post "signup", to: "users#create"
  resources :users, except: [:index, :destroy]

  namespace :admin do
    resources :users, only: [:index, :destroy, :show]
    resources :subjects
    resources :questions
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>© <%= l Date.today %><%=link_to t "layout.footer.title" %></p>
  </small>
  <nav>
    <ul>
      <li><%=link_to t "contact" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("layout.header.logo"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("layout.header.home"), root_path %></li>
        <% if logged_in? %>
          <% if current_user.is_admin? %>
            <li><%= link_to t("layout.header.allusers"),
              admin_users_path %></li>
            <li><%= link_to t("layout.header.subject"),
              admin_subjects_path %></li>
            <li><%= link_to t("layout.header.questions"),
              admin_questions_path %></li>
            <li><%= link_to t("layout.header.exams"), "#" %></li>
          <% else %>
            <li><%= link_to t("layout.header.exam"), current_user.name %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t "layout.header.account" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("layout.header.profile"), edit_user_path(current_user) %>
              </li>
              <li class="divider"></li>
              <li><%= link_to t("layout.header.logout"), logout_path,
                method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("layout.header.login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", 
  "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>